apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservices-demo
data:
  JWT_EXPIRES_IN: "15m"
  REFRESH_TOKEN_EXPIRES_IN: "7d"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  KAFKA_BROKERS: "kafka:29092"
  ELASTICSEARCH_NODE: "http://elasticsearch:9200"
  SMTP_HOST: "mailpit"
  SMTP_PORT: "1025"
  SMTP_FROM: "noreply@microservices-demo.local"
  CORS_ORIGIN: "http://localhost:3000"
