apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: microservices-demo
  labels:
    app: search-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: microservices-demo/search-service:latest
          ports:
            - containerPort: 4005
          env:
            - name: SEARCH_SERVICE_PORT
              value: "4005"
          envFrom:
            - configMapRef:
                name: app-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
