apiVersion: v1
kind: Service
metadata:
  name: task-service
  namespace: microservices-demo
spec:
  selector:
    app: task-service
  ports:
    - protocol: TCP
      port: 4003
      targetPort: 4003
  type: ClusterIP
